FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# Vars VITE_* são injetadas no build via build-args do EasyPanel
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_URL
ARG VITE_APP_URL
ARG VITE_ENABLE_TESTS
ARG VITE_N8N_SEND_GROUP_MESSAGE_URL
ARG VITE_N8N_CHECK_GROUP_ENTRY_URL

# Disponibiliza no ambiente do build para o Vite
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_APP_URL=$VITE_APP_URL \
    VITE_ENABLE_TESTS=$VITE_ENABLE_TESTS \
    VITE_N8N_SEND_GROUP_MESSAGE_URL=$VITE_N8N_SEND_GROUP_MESSAGE_URL \
    VITE_N8N_CHECK_GROUP_ENTRY_URL=$VITE_N8N_CHECK_GROUP_ENTRY_URL

RUN npm run build

FROM nginx:alpine AS runner
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
